### ISSUE TITLE
[feature for consideration] Read wkt_geom in xlsx such as multipolygon(((...

### ISSUE THREAD

**Issue by gp-agtech** [camptocamp/QGIS-SpreadSheetLayers#24] opened 2021-06-14 05:16 UTC
This might not be the issue but rather the feature I am looking for.

Problem statements:
wkt_geom saved in csv is limited by character length for each cell. I have a wkt_geom with very long string saved in xlsx.
However, I finding difficulty to find some plugins which can open the xlsx file as vector.

It seems that the spreadsheetlayer only work for point(x, y) and the coordinate have to specify in X and Y fields.
It will be good if ir can specify wkt_geom (single column) as feature geometry and support other types of geometries.

**Comment by mki-c2c** [comment] 2022-04-08 11:12
linked to #20

**Comment by mki-c2c** [comment] 2022-04-08 11:15
Best way would be to use the same GUI as for csv layers:
- Point XY
- WKT
- No geometry

I'll check if it is possible to use the GUI from csv layers without modifying the QGIS source base, so that the functionality is available on old QGIS versions.

**Comment by mrsmithsd** [comment] 2022-05-19 18:26
> Best way would be to use the same GUI as for csv layers:
> 
> * Point XY
> * WKT
> * No geometry
> 
> I'll check if it is possible to use the GUI from csv layers without modifying the QGIS source base, so that the functionality is available on old QGIS versions.

Did you succeed ? I also want to use the spreadsheet layer plugin but for polygons. A wkt entry would be nice!

**Comment by arnaud-morvan** [comment] 2022-08-21 16:32
I've stated working on WKT support: #37
It will be in next release.
But this is a duplicate of #20, so I close this, please follow #20 if interested.

**Closed by arnaud-morvan** 2022-08-21 16:32 UTC
Labels: enhancement
